### PR TITLE
ADD: Weds-nipreps-esteban

### PR DESCRIPTION
**Pull request by oesteban**
Finishing up my materials. Will make a final PR when things are ready.

### CODE REVIEW

**Comment by arokem** [comment]
Sorry: I accidentally hit the "ready for review" button. This is still WIP!

**Comment by arokem** [comment]
@oesteban : just let me know (here or per DM on slack) when you want this merged.

**Comment by oesteban** [comment]
@arokem ready to go! thanks!

**Comment by arokem** [comment]
Thank you!

**Pull request merged**
